### ISSUE TITLE
UI address input issue

### ISSUE THREAD

**Issue by rafaelfernandezgis** [urbandataanalytics/udaSearchBox#21]
By default, always appears the cross icon over the cadastre button. It is not a good UI implementation. I suggest to move it inside the address search field, on the left of the buttons, keeping always it a few pixels away from the address icon button.

![imagen](https://user-images.githubusercontent.com/6051197/45549949-cd293580-b829-11e8-8be6-8dc9889608f4.png)

**Comment by valromo** [comment]
already solved!! thanks Rafael!
