### ISSUE TITLE
Project fonts

### ISSUE THREAD

**Issue by rafaelfernandezgis** [urbandataanalytics/udaSearchBox#22]
It would be great if the project uses the designed **Gotham** font or every item inside this component, which includes the search box field. Something like this:

![captura de pantalla de 2018-09-14 14-32-16](https://user-images.githubusercontent.com/6051197/45550426-17f77d00-b82b-11e8-8cc8-d56d30f8b0ba.png)

**Comment by lauraVzarco** [comment]
this issue was closed in https://github.com/urbandataanalytics/udaSearchBox/pull/26 :dancer:
