### ISSUE TITLE
Error displays between options

### ISSUE THREAD

**Issue by RominaMartin** [urbandataanalytics/udaSearchBox#32]
If there was an error while obtaining either address or cadastre and you click on the other item it will display the error for the new one.

ie: I search an empty address -> Address error is displayed (:+1: ) -> I click on cadastre -> Cadastre error is displayed (:-1: )

I'm guessing expected behaviour should be dismiss errors if another input type is selected.

**Comment by valromo** [comment]
I think the issue is solved now on #34 
thanks!
